name: Dispatch Promote

on:
  workflow_call:
    inputs:
      version:
        description: "Release to promote"
        type: string
        required: true
    secrets:
      DISPATCH_TOKEN:
        required: true
      
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch promote event to test-dispatch repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: "yalp/test-dispatch"
          event-type: test
          client-payload: >-
            {
              "app_repo": "${{ github.repository }}"
            }
