name: Dispatch Promote

on:
  workflow_call:
    inputs:
      version:
        description: "Release to promote"
        type: string
        required: true
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch promote event to test-dispatch repo
        env:
          GH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
        run: |
          gh api \
            repos/yalp/test-dispatch \
            --method POST \
            --field event_type=test \
            --field "client_payload[app_repo]=${{ github.repository }}"
