name: Dispatch Promote

on:
  workflow_call:
    inputs:
      version:
        description: "Release to promote"
        type: string
        required: true
      environment:
        descrption: "Target env"
        required: true
    secrets:
      DISPATCH_TOKEN:
        required: true
      
jobs:
  dispatch:
    runs-on: ubuntu-latest
    environment:
      name: $‘{{ inputs.environment }}
      deployment: false
    steps:
      - name: Check secrets
        run: |
          echo "Test: ${{ toJson(secrets) }}"
      - name: Dispatch test
        env:
          GH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
        run: |
          gh workflow run dispatch.yml \
            --repo "yalp/test-dispatch" \
            --ref main \
            --field app_repo="${{ github.repository }}" \
